### ISSUE TITLE
Creating movie output at source resolution

### ISSUE THREAD

**Issue by hbfs** [153957/time-lapse#119]
Hi @153957! Thanks for creating and sharing this awesome repo for making timelapse videos from images!

I was able to get it to work using the defaults which creates a scaled 1920 x _ and 960 x _ with great deflicker'ed output! 😃 

I had a few questions:

1. Is there a way to easily and only create video output at the source resolution, without modifying `output.py`? I can't seem to override the output. Even if specifying a blank [] filter, I'm probably doing something wrong here. Perhaps I need to pass a `copy` filter?  

2. How can I use the ffmpeg-python bindings to use a list of images instead of a pattern? I'm pre-filtering the images based on brightness criteria and generating a list if images and paths to use.
I'm able to do it on the cmdline with : `ffmpeg -f concat -safe 0 -i imglist.txt  -r 30 -crf 20 -movflags faststart -pix_fmt yuv420p -preset slower timelapse-output.mp4`  thanks to https://stackoverflow.com/questions/67151665/can-i-pass-a-list-of-image-into-the-input-method-of-ffmpeg-python

3. In an effort to solve the above two problems, I resorted to the cmdline but I'm not able to get deflicker work. I studied the output of the repo thanks to the verbose command but have not been able to get it to work. I added `-vf "deflicker=mode=pm:size=70"` results in all black output 

full command: 
`ffmpeg -f concat -safe 0 -i imglist.txt -vf "deflicker=mode=pm:size=70" -r 30 -crf 20 -movflags faststart -pix_fmt yuv420p -preset slower timelapse-output.mp4` 

I've also tried filter_complex with the same results (black video):
`ffmpeg -f concat -safe 0 -i imglist.txt -filter_complex "[0]deflicker=mode=pm:size=70[s0]" -map [s0] -r 30 -crf 20 -movflags faststart -pix_fmt yuv420p -preset slower timelapse-output.mp4`

Any advice here would be helpful. Please let me know if the ffmpeg mailinglist or elsewhere is more appropriate.

Thanks and best regards.

**Comment by hbfs** [comment]
I was able to solve everything:

Use deflicker of `7` not `70`!!

1 & 2 & 3:
With `ffmpeg-python`:
```
(
ffmpeg
    .input('imglist.txt', r='30', f='concat', safe='0')
    .filter('deflicker', mode='pm', size=7)
    .output('video+deflicker.mp4', crf=20, preset='slower', movflags='faststart',pix_fmt='yuv420p',vcodec='libx264')
    .run()
)
```

Hopefully this helps someone else!

**Comment by 153957** [comment]
I am glad you solved it!
Most of the (default) settings uses are indeed a bit specific to my own setup, I could have made it all more customizable, but this was simpler. If you see value in using this package if the output is a bit more customizable I can probably adapt it to make overriding easier.
